apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: city-gallery-next-mailgun-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MAILCHIMP_API_KEY: AgAciLT5RjgxDWCzo0MTUV/Fh2vpW5LOZjIWz09qtAw9Wqff9QA0//VW5ADbmojZLGJLcqxxMiPFc8tGDr4pRbpLPx+Th4weRj4otGe0qOSGRni/34SmqE1EVZrrW5S47cGGKG6f3HDPeMN4R/8p+kQYeHpK0KrZ6q6luMtAUn5KFXPtqpT67Hi7d82yBNQaMu/sHKbeTSoCGcTe3rmlkrDCMu6KMwwoU9tAXDW0ylmKQPX7uVfNDAnsz+hqL2HS348hGn4RJwYZhBtKiU2SV+9w9J2MjakuJoaZ5lm+QGSnfBfjelkY8Fv5xqRuY/yA1DZACLkl16HADY8UmlENeY9GcSH6UnaZu6YtvB5jGWGbtL2T+mHWGshUA73tyR5CRDqlrKJMrRHVR6lmqCRKjQRGwdnyZMmFpg4xvkfi9GdzLPpeKSYaQoaSNYAGuCbCS6za7MHlCpzkdQUyqOA2wv+x7s7MUpt93yYLaRJAicPStgSi8PIIl+lh53E712IWw91VGIMKKuQOpaScQ3lQVlRctHXKOeT7rglkGW7Gyz0bwiKgZHeATMCgFyOhE2Wvk5CyVStb+jcC7uHfOTvStmHD7M1YlPYrt4HrC8mH+3r0H9Q4aL3wEnmSZJJrzV/RoWStwLVRiVNzthCiTBQ+W6c09z31tXQ3qUYg0n4zmmQ2e0MAzomoUQaDsVDQO5ivTR9LVJsenc4OJhS8YHXEtx8tXnS6etiqKGML6DPyInaYKCFt0/I=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: city-gallery-next-mailgun-secret
      namespace: ${NAMESPACE}
