apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: city-gallery-next-mailgun-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MAILCHIMP_API_KEY: AgC57YvT8rapRgP6G5LE+2Wcoz5S0vVsPlzzSLf5EANCzreU3hBN3Y7WBrlyMH7FfAVPpiy3hAwKupCoomroHQ4XAh/jVqpa9h3GzFuwXkpWQ6KRzs7/ZZyl3IEaPkr3k448Rkln/LHc+/juZ+K2sj+IaQvZ3F5US9+N+A/IBX7dO8T/r7hUpNJ1mROLIfwzhopZyyGIIJQQBrmQbJD9WOtL61deCvpGe/yTdoqu8XbtHVeiNlpRuXmMR97sOWzDFZpySdHz3WuO/MFmyHSukFCghhjRwIRCIidg4zua3sOghruQnnX5bSO6jtg1QB6vF9TVkiTC6iG0aMl3YHDNqvl8dUhmWi3aHh/XWO0xvKwj7qtAP99jYswHypnhGtoHlQyHotp+ZOe/j26tRTGrqixSPAHoPH4XYdBJRa0vQfXX618pMGsBDgdyV0KdAwCxY9a6V5WWeyGakcQ6/lwvC/mc0wZmpayB8SPIfZjKXVWWRSzeue4GGtKZKyZIWFwPZO3k+VxsK64maXbVWhZTDV1lbYl/UjctUsRZJd0H+Uu1kB5O8Otuhgrg4N5os3pdQqqVaikSe4pw3xe7+d7JNXOBTDV/lHtzyP7TTkaZECCD9jBumQP2bGI3gmySVdzEeY24qFLdVu+iIbuTyFzxri2vA/AQK69BxEMXv2/ZWjQJr5ZR4LUVbOtruzOgSI2q3SYc23cpKQ4e+IMOmVUni5RsYZwtdSGUe49CkG9l4p/KvwsdKB0=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: city-gallery-next-mailgun-secret
      namespace: ${NAMESPACE}
