fragment ImageEntity on UploadFileEntity {
  attributes {
    url
    alternativeText
    width
    height
  }
}

fragment ImageWithFormatsEntity on UploadFileEntity {
  ...ImageEntity
  attributes {
    formats
    caption
  }
}

fragment TicketEntity on TicketEntity {
  id
  attributes {
    title
    price
    description
    purchaseIdSelf
    purchaseIdGift
  }
}

fragment PartnerEntity on PartnerEntity {
  id
  attributes {
    title
    logo {
      data {
        ...ImageEntity
      }
    }
    link
  }
}

fragment TagEntity on TagEntity {
  attributes {
    title
    slug
  }
}

fragment PlaceEntity on PlaceEntity {
  attributes {
    title
    address
    slug
    purchaseId
  }
}

fragment Position on ComponentBlocksPositionItem {
  title
  names
}

fragment Datetime on ContentPage {
  dateFrom
  dateTo
  timeFrom
  timeTo
  showRemainingTime
}

fragment ContentPagePlace on ContentPage {
  place {
    data {
      ...PlaceEntity
    }
  }
  placeTitle
  placeAddress
}

fragment Positions on ContentPage {
  positions {
    ...Position
  }
}

fragment Partners on ContentPage {
  partners(pagination: { limit: 100 }) {
    partner {
      data {
        ...PartnerEntity
      }
    }
  }
}

fragment SliderSection on ComponentSectionsSliderSection {
  id
  submenuTitle
  medias {
    data {
      ...ImageEntity
    }
  }
}

fragment Seo on ComponentBlocksSeo {
  metaTitle
  metaDescription
  keywords
  metaImage {
    data {
      ...ImageEntity
    }
  }
}

fragment Links on ComponentBlocksLinks {
  title
  links {
    title
    url
    newWindow
  }
}

fragment ContentPageEntity on ContentPageEntity {
  id
  attributes {
    title
    titleToShow
    subtitle
    useDatetimeAsSubtitle
    slug
    addedAt
    coverMedia {
      data {
        ...ImageEntity
      }
    }
    perex
    color
    inheritColorFromParent
    ...Datetime
    ...ContentPagePlace
    ...Positions
    ...Partners
    sellTickets
    purchaseId
    showShareButtons
    mainContent {
      ...MainContent
    }
    slider {
      ...SliderSection
    }
    relatedContentTitle
    relatedContentSubmenuTitle
    downloadSection {
      ...DownloadSection
    }
    parentPage {
      data {
        attributes {
          color
        }
      }
    }
    childPages {
      data {
        ...SectionItemEntity
      }
    }
    tags {
      data {
        ...TagEntity
      }
    }
    seo {
      ...Seo
    }
    localizations {
      data {
        attributes {
          slug
          locale
        }
      }
    }
  }
}

fragment CommonSearchPageEntity on ContentPageEntity {
  id
  attributes {
    title
    slug
  }
}

fragment ExhibitionArchive on ComponentBlocksExhibitionArchive {
  title
  subtitle
  perex
  color
  coverMedia {
    data {
      ...ImageEntity
    }
  }
}

fragment NewsItemEntity on ContentPageEntity {
  id
  attributes {
    title
    subtitle
    addedAt
    useDatetimeAsSubtitle
    slug
    color
    inheritColorFromParent
    parentPage {
      data {
        attributes {
          color
        }
      }
    }
  }
}

fragment SectionItemEntity on ContentPageEntity {
  ...NewsItemEntity
  attributes {
    perex
    coverMedia {
      data {
        ...ImageEntity
      }
    }
    ...Datetime
    tags {
      data {
        ...TagEntity
      }
    }
  }
}

fragment HighlightsItemEntity on ContentPageEntity {
  ...SectionItemEntity
  attributes {
    titleToShow
    ...ContentPagePlace
    ...Positions
    sellTickets
    purchaseId
    override {
      highlightContent
    }
  }
}

fragment Highlight on ComponentBlocksContentPageItem {
  contentPage {
    data {
      ...HighlightsItemEntity
    }
  }
}

fragment DownloadItem on ComponentBlocksFileItem {
  id
  title
  file {
    data {
      attributes {
        name
        caption
        alternativeText
        ext
        size
        url
      }
    }
  }
}

fragment PalaceDetails on ComponentBlocksPalace {
  title
  address
  zip
  city
  phone
}

fragment GeneralEntity on GeneralEntity {
  attributes {
    name
    email
    openingHours
    mirbach {
      ...PalaceDetails
    }
    palffy {
      ...PalaceDetails
    }
    socialLinks {
      ...Links
    }
    footerLinks1 {
      ...Links
    }
    footerLinks2 {
      ...Links
    }
  }
}

fragment ContactCardEntity on ContactCardEntity {
  id
  attributes {
    name
    position
    email
    phone1
    phone2
  }
}

fragment OpeningHoursSection on ComponentSectionsOpeningHoursSection {
  id
  submenuTitle
}

fragment PageSection on ComponentSectionsPageSection {
  id
  title
  submenuTitle
  layout
  contentPages {
    contentPage {
      data {
        ...SectionItemEntity
      }
    }
  }
}

fragment NewsSection on ComponentSectionsNewsSection {
  id
  title
  submenuTitle
}

fragment NewsletterSection on ComponentSectionsNewsletterSection {
  id
  submenuTitle
}

fragment RichtextSection on ComponentSectionsRichtextSection {
  id
  submenuTitle
  content
}

fragment VideoSection on ComponentSectionsVideoSection {
  id
  title
  submenuTitle
  url
}

fragment AudioSection on ComponentSectionsAudioSection {
  id
  title
  submenuTitle
  url
}

fragment GallerySection on ComponentSectionsGallerySection {
  id
  title
  submenuTitle
  medias {
    data {
      ...ImageWithFormatsEntity
    }
  }
}

fragment ContactCardsSection on ComponentSectionsContactCardsSection {
  id
  title
  submenuTitle
  contacts {
    contactCard {
      data {
        ...ContactCardEntity
      }
    }
  }
}

fragment TicketsSection on ComponentSectionsTicketsSection {
  id
  title
  submenuTitle
  text
}

fragment MapSection on ComponentSectionsMapSection {
  id
  title
  submenuTitle
}

fragment DownloadSection on ComponentSectionsDownloadSection {
  id
  title
  submenuTitle
  files {
    ...DownloadItem
  }
}

fragment ArchiveSection on ComponentSectionsArchiveSection {
  id
  title
  submenuTitle
  archiveCard {
    ...ExhibitionArchive
  }
}

fragment Sections on VisitUsPageSectionsDynamicZone {
  ... on Error {
    code
    message
  }
  ... on ComponentSectionsPageSection {
    __typename
    ...PageSection
  }
  ... on ComponentSectionsNewsSection {
    __typename
    ...NewsSection
  }
  ... on ComponentSectionsOpeningHoursSection {
    __typename
    ...OpeningHoursSection
  }
  ... on ComponentSectionsNewsletterSection {
    __typename
    ...NewsletterSection
  }
  ... on ComponentSectionsTicketsSection {
    __typename
    ...TicketsSection
  }
  ... on ComponentSectionsMapSection {
    __typename
    ...MapSection
  }
  ... on ComponentSectionsRichtextSection {
    __typename
    ...RichtextSection
  }
}

fragment MainContent on ContentPageMainContentDynamicZone {
  ... on Error {
    code
    message
  }
  ... on ComponentSectionsRichtextSection {
    __typename
    ...RichtextSection
  }
  ... on ComponentSectionsVideoSection {
    __typename
    ...VideoSection
  }
  ... on ComponentSectionsAudioSection {
    __typename
    ...AudioSection
  }
  ... on ComponentSectionsGallerySection {
    __typename
    ...GallerySection
  }
  ... on ComponentSectionsContactCardsSection {
    __typename
    ...ContactCardsSection
  }
}
