query General($locale: I18NLocaleCode!) {
  general(locale: $locale) {
    ...GeneralEntity
  }
  menu(locale: $locale) {
    ...MenuEntity
  }
}

query Places($locale: I18NLocaleCode!) {
  places(locale: $locale) {
    title
    slug
    address
  }
}

query TagsByCategorySlug($locale: I18NLocaleCode!, $tag: String!) {
  tagCategoryBySlug(locale: $locale, slug: $tag) {
    tags(sort: "id:asc", pagination: { limit: 100 }) {
      ...TagEntity
    }
  }
}

query News(
  $locale: I18NLocaleCode!
  $tag: String!
  $limit: Int = 5
  $sort: [String] = ["publishedAt:desc"]
) {
  news: contentPages(
    locale: $locale
    sort: $sort
    pagination: { limit: $limit }
    filters: { tags: { slug: { eq: $tag } } }
  ) {
    ...NewsItemEntity
  }
}

query PreviewsByTags(
  $locale: I18NLocaleCode!
  $limit: Int
  $offset: Int
  $tagSlugs: [String]
  $placesSlugs: [String]
  $dateForFilteringPastEvents: Date # pass either this or dateForFilteringFutureEvents
  $dateForFilteringFutureEvents: Date # pass either this or dateForFilteringPastEvents
  $sort: [String] = ["dateFrom:desc", "publishedAt:desc"] # keeping this default sorting as it was before
) {
  contentPages(
    locale: $locale
    pagination: { start: $offset, limit: $limit }
    filters: {
      tags: { slug: { in: $tagSlugs } }
      place: { slug: { in: $placesSlugs } }
      or: [
        # if dateForFilteringFutureEvents is passed, we get all events with null dateTo, and dateTo greater than dateForFilteringFutureEvents
        # if dateForFilteringPastEvents is passed, first condition is always false, and we get all events with dateTo less than dateForFilteringPastEvents, so events with null dateTo are filtered out
        { dateTo: { lt: $dateForFilteringPastEvents, null: true } }
        { dateTo: { lt: $dateForFilteringPastEvents, gt: $dateForFilteringFutureEvents } }
      ]
    }
    sort: $sort
  ) {
    ...SectionItemEntity
  }
}

query PreviewContentPageBySlug($slug: String!) {
  contentPageBySlug(slug: $slug, locale: "all") {
    slug
    locale
  }
}

query ContentPageBySlug($locale: I18NLocaleCode!, $slug: String!, $isPublished: Boolean!) {
  contentPageBySlug(slug: $slug, locale: $locale, isPublished: $isPublished) {
    ...ContentPageEntity
  }
}

query AllContentPageSlugs($locale: I18NLocaleCode!) {
  contentPages(locale: $locale) {
    slug
    locale
  }
}

query MainPageBySlug($slug: String!, $locale: I18NLocaleCode!) {
  mainPages(filters: { slug: { eq: $slug } }, locale: $locale) {
    ...MainPageEntity
  }
}

query AllMainPageSlugs($locale: I18NLocaleCode!) {
  mainPages(locale: $locale) {
    slug
    locale
  }
}

query Tickets($locale: I18NLocaleCode!) {
  tickets(locale: $locale) {
    ...TicketEntity
  }
}

query ExhibitionsByPlace(
  $locale: I18NLocaleCode!
  $slug: String!
  $today: Date!
  $tagExhibitions: String!
  $tagPermanentExhibitions: String!
  $place: String!
) {
  currentEvents: contentPages(
    locale: $locale
    filters: {
      or: [
        { tags: { slug: { eq: $tagPermanentExhibitions } } }
        {
          tags: { slug: { eq: $tagExhibitions } }
          or: [{ dateFrom: { lte: $today }, dateTo: { gte: $today } }, { dateFrom: { eq: $today } }]
        }
      ]
      place: { slug: { eq: $place } }
      slug: { ne: $slug }
    }
  ) {
    ...SectionItemEntity
  }
}

query HomePage($locale: I18NLocaleCode!) {
  homePage(locale: $locale) {
    __typename
    highlights {
      ...Highlight
    }
    sections {
      ...HomePageSections
    }
    seo {
      ...Seo
    }
  }
}

query ExhibitionsAndEvents(
  $locale: I18NLocaleCode!
  $today: Date!
  $tagExhibitions: String!
  $tagPermanentExhibitions: String!
  $tagsAdditionalProgram: [String]!
) {
  exhibitions: contentPages(
    locale: $locale
    filters: { tags: { slug: { eq: $tagExhibitions } }, dateTo: { gte: $today } }
  ) {
    ...SectionItemEntity
  }
  permanentExhibitions: contentPages(
    locale: $locale
    filters: { tags: { slug: { eq: $tagPermanentExhibitions } }, dateFrom: { lte: $today } }
  ) {
    ...SectionItemEntity
  }
  additionalProgram: contentPages(
    locale: $locale
    filters: { tags: { slug: { in: $tagsAdditionalProgram } }, dateTo: { gte: $today } }
    sort: ["dateFrom:asc"]
  ) {
    ...SectionItemEntity
  }
}
