apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MAILGUN_API_KEY: AgBnAi7OZ6yjsr050kFjtrKhFJqQj0SJyZxm/4PUuiqzXOdw4nmvO9z/HXvH2B2+oadYf0vp2Ak0813MWhi4OrJtOXKg4Wn7TFQyE77092GiFVycZ9zGES0kzMJWtaUdsW/gArc51JbES4AT2z4R/bzh0VSGCFPl6wOsdUqVKYqSl8dFf2LtCp49kWSGy9GswPd5NVlVFQmJ4Fq3rZVKsVcwTnAAeMvgojX7dEEfhz6Q5gU4POkeJKkVEoFCkVatCS0zdvH47AriX9qfX7XlDDQvR6WSHDGyZ3EnLEoj6TnjknRDHV3Tof4NVv2e/Z09ottuQxmDyFYYe2wDDU2dR/GF41FqsIrDPL/pu7xsQWLeb8MhgadBYYjU6dYniEWlV/mIFiicMfRhx3cb6g7eFpGJ2tF8MCLQoMvCCrvXj+nQuXdG/6C2sgQhHwFqTvxHo8mFYbkj3rVqMMV7uD8Lg63sTLQnsU9qVxXRAvkyS806fDnDyay+D3EA4+D9oX5wDNmwn7fjF/CJ7s0jtoAnl5JixxUJOhjI6etDn3qiwVnPNwvvfhXZoyoXoDP18zccrzZdz3HTfr2YrJinCkWcjNstRoGN7rnfDx7OIvdfEgzP+aCmyIHcAE/MYCqUNW6AD2BljkrwTMW+avLXefPVsZlMk45OG821hGzscDJZ7trkRERdJ3WafmKTJPrCSH3BZRexFSu3MI0YCWHe7h1lROfi0AbWnGnxnMgXX5fr7X3m2yh1oBcKHzXwqKszOCW94CDBNQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: ${NAMESPACE}
