apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgCvAXwQFXk+5XOfCJK7GLWNF8mQAxy7QkaE2/rD3HhniwYNWt9R/po5GjxPkkxpIoiEofYQgUXoNs0LVOOeMEMFlp9LnIdUbm49f1VYJcXhaav3HDOl84sYDBZPt1SVaKODxYnKb9AbRRyiVkz/y+E49RRTTHHUHwvj0Im0mGi+w83/AKw/qny+7qn2Ratwa2kWqd/vgr9u1Paq4YRWpJQkLfUk6HLHf26SSvSoDfwci32m9pPTqfIhsn4xF4vw35B1Q9Z4wlfYa42Ra67+gUQHXThvGkRPHVHUvW9lpid1i5hP5rUaYEZbnPoAoaW0Nc+EvzyzjMuxz+Ps5AQK3AqrRUfdZVn2MLOn94PeM0rkSdhaqZsiDliklKeqwUk9xYpVGo0NXqMFrF8Rr3pJ5YtmhVW+9puCYROAjFeKyYogEYmhM6UC1T2h1pSUVNRAhjvVoLsvcqfbFLkKuAIRi0yiVDgKqgXXlozUX/UlXtaBJX1O7XgkaLphwNEOKueXlQInlIWoCSij+ittZTJEnQTzEIz7tPbJc1T2dE7/w3lI8JzNj1qPqWLfPcVnUIpX5QmRkQrcRObo9LiHOseYYwhlGz/FnVV1AUljwqvYDl/rhKaGZQ049ZAHfkoIlGJUxJLWx9Q7Nr7o9OYIvlhmJ01aE51COuM1oiTGuAbU5Y5UR16JPV5s0gXGkxUMc/LtKsM8p9Py6DlqXo3+ZwBetlSUlkf6bGaiz8FoNbctcAMOqg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
