apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgBAya/seZpYnn6FZNKIhTcGJ8LVXgaK4AOYWBcxVeGyvZBq7KFmgSJRPnaRKdd1b/eDLMXeM/6Dy8RUYWfKs9603btmUJ2d1YCyx9V0Wkx5/APyrdPLlhectfJRaF1XBE/3SlJ6E9CRXJD+LqPF4t2BbiRODCi/8++MUl+gF0NLZO82lo2ttf0dgR7UlrENKh/8mZfFX3quyrIlro3qwAPj14iad6zknZSfp0Qjtsk3/AksAp4mMSCiY5y/1pPbWVDQ91/dTqK5TTF4g7nSULJVncQzzQg2aRgpg7L+EQBcmjE79Yy8yYGrLWL2cG8sYBMgkmQlrUxhHHB0n+TDyFJdoaVZ5lZPvayxNj7nYMwNJldC0V5ftjka9wbwVSfPezwqxZmVmbv0DuApq8ypi5ViPbMrdrbJJJSEQViitvgU+M79wgDV5v2y+/cvTEzhQ9fl7Pj6WeNHuRdPXWmEW9p58sZajm6eNMtSZ8L1su11lY5t+MWR70LXsKHsHdGpbg2GHwXU90YiGhb+NYunF5i9hrnx8AGY4rTugdBSuU72ZutkgNGYSU9lH21R7BHmXztm6vSWQd5bZimZURQxLOyyRmawZ6X8zYuZMF4nWy9NllBFFRyyWb85g5k6801ziJxTxpmLX9TXBgkQhZtQVuv12Fx2q/tLrJe/FkOIVgcSPdf/Bwm3ZORWrjApVP3oQO7JHmtGBkAFRzZF52rXJq/CfLIgDDtH8kMrLsg6d+QH
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
