apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MAILGUN_API_KEY: AgBlAQG7d59iJmWDMtO6JMdhpZI8Tsy2G7eJgHXiyRa1c/zBa6YBwh3f8eTFC/syRdgAtF6gKBft17Zg+U7gxGgoTHzT0Qk/77JNp9CzqA2+3/0UM2+oqiWZdtHzdVAqZO6Dqcg2ddISJoQ20SjcaLn/8sYT1tJnCEjlYDS8xg15xs2XI4b4U4SREBuzwJ4R4khyedF4UjpTImArqjdU3LpAD7RQOdIVbu907MMtG1LHWYNELO8xRJOh/3DH3w72HLPQo07s03j5UAqsqYaLsUxRi5V52z1W55wHHRGzOCCz3V4JsWpeR74KLHtohzsn5v/NxDojfJgNLOZN2CJOrQQ1ls92Ao1s1QK8uf5A/OKvKKwzu7tPqZ4uIrPDnvRrbu2L2zvTrfE9CBgnAft/3lAJVpRCvTcFhlWc2BzzgVaQwvLgWwucqVv3nVycuZ8NxDZN5c9qx6ZRgeXWW5EMntanWlmt1o0RLwxYFhN6leWqcUyDA76QTzvjaDAgO8YUQgNh2WCHqzerSPcVyWXJ/WvUSf+jIiEv71U//qWlTaURTeuT/vScIIwfafM/VX9PI4IqD0qP1hj697q1XRnD6m88wRFTqtFgYunJEBC1IsBYUWvVS/MiI+/yURBMS7BMDvR+MwG4KC7G1D4+KShvor1rQ/7UoBPBUWdy0n62baj61ypWnLHQZz217trY87YRJWz+0oaUkpEQnvhBviywT0Wci27BzjO3yUgViI3uIkzlCvWxlmSRUB71mDb+VDpmD+pL8g==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: ${NAMESPACE}
