apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: city-gallery-strapi-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgA1kSFDsYjUR1fs/k/kjZDckpLXYt70R0Eb8EduAYEssrM5ps3AGIOo/SEyK3OC5ZHINQnyuVD1MVVA2vil54iVGgHnC1mEOB3d71ALziJW86TCQDUpyTFsfdHgFrqiiIy6bPULQZjsQkrPa/I7x+mi91ZIvV9iCNBJhiSKLuMRCR8PCDPdKDsB0XsG8H8nli4Y4ZePJ+0DOnQ1o5aWvAYhgdW3AVZfHpay4s91Q0T9CwroaaOHZ+E1I6zC7p5Bp0JgnAv4LFr2zHkeN77m80Qk2AKPd+jmScS/n9koz0Kxk4HmD2QuP+ZSU2G3uH/nHd7DMNZ6iUxMgLQAB5yq7Dw2eNJNxXB9GPxOBpYOSysaFLuN1n+wR7D9cstFoMQkXlgN8vX3OLKNB0dHCi2MLBcaM7siYZuw5nisSh+5kpmUXqA533m28CQQA2bUCbPyCvDcBeeb1lPxa8zNMK1NmBD7XjKT8Y2tCWXQiMPreTI87nurlWI+HXVg2c35aASQayHjdTHA8fNguIHrOmrMs681CP51WXGZvjNnhbwfrrsoM1ljTZDpZoOEv2soAWHX9KMpa0kqYrYu0kVvgx2F/gtMaIVLbmwi9DZGSLb/Jp5CCVoVpQMGMT3yJoOTKistmwUufreautzPkp0lzKnIaqwU/CxklykdVbNnWiu5CoEkCKL8BMCr3bmpHaIMvc8USXYXR6k=
    MINIO_SECRET_KEY: AgB7m2n91B8zuUemsLxBXuqikf/s1q8/TH5nZI+9cIZ5hGTJtsmzaBysSv67w+KXzU5wgV2/SZyZjGGnrBRnvB2Efaqsiuwq3SRqQxdsH8hYox0P4wwiEp6CFASU20oVptX1gDyezdwvpviFoaWQ9SN6UJLGEgTslTGR+3BqC8m+o/W7HptYF8zhrjO1KqYSp00WWXBjTELaG6YkOEgoxbjKWj1dMuHDqV7v4odg7vNebvM6HOPFZHv1GxZp9alVeqNLb7gVTXLZUiULinuM4sA5Pz99pj1CMCOfUhUrcHjndi/5xQLTjhzbfNth1QmdhQUourp8KBVIWLfnlW4PPZVtoJE8Qq9CnTjZ24FOrZ9mauanX2Y8G4MGHpyxgM22omOeNSxL8I2p36qocr/byltnZ6+eAohVa1klbEoIAZ9VtgE3JkiXJVyb6tVL1twMQ2cIJb60O4/TmE90PId82nmd8tLRbu+F6dchl7xjPwxvLddQtaNsBPUfmNzQFtEbvcCiYxP+HulLB0JN2SeZylaIkI5sHrSSQRb7M6/uJkkW+2aM15isFX4GNd5UCeFWx6kEh8jgZF4tg3ZhDKbKA8rUJAFz+POC12QHRKfzacwDiPZmviiaqfIeTEaFl9LO9QXnkVpZxtEhur5Afp05kTO5RpxKAuyy++M+vPI+oVMqBpgniNYvQINu7ct1TZVQaPRJ5d7qfefv2wN0evvH6vV/bybHjMxw4/Qnuzr9QoyUTQb7SA1mJsj0j4lVwDpJ+bydg/5ReKKnHA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: city-gallery-strapi-minio-secret
      namespace: ${NAMESPACE}
