apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgCex5sGeJI7fgYZhmgGxXVtvILJAlf9gB0oCiMspZwSJO1oTF7qwuENJb1PHWCqwkdu2JISOWupXbUHAqoHOs0rwjE7I2UIoMkerpxi+z2mNbzZCS385pYy3WQi+hvg8Pg34PfIGG5cEjiWBYa4o1IFlLNUuB9Xjm7ZnpXf9l3q07rhIrhyEZAdjBJ7cjCJ2MgjVmEishEzAa68zTsclCOJGwe5IHMNoCfsh/cwXFYARYC/NI6cxj5oMTprmLhASEcviBsfyJ8QUbywIeq1WhDWL2RA3HOelIqt0CNH5mFyzm6EA1dmkN9sL5Mll9uMgv8TjoUH5Fj6qeoR6xF0QqDsi/1AyK41m+Lus9bRLZBDoeRY0sKPhp3BKsyQbZPLG+2e9DUc3vv/3KBBwOdckQPnO2UbIq00BwFO9CQGR9T0CWoEwyaXXZxg1a/n+aH7V5/xC1zvNm9BMGT4LcneIc2fDcBviuG2P/lrNW0z0PBbivyteJgsTACdIkc8iF1ww1Y1GUHcezYqZUZtgYSOb35s36IK2Bs2v6BHT0D3Nj/3VVFnqa3hhuQt2YKXZZzeo4e8KI/Xrr5j1nD/MtQuYIAzYfMuMPGJFGI9qeINd2n08PCNoRU93K7VxNA1XFwg5OEhzGCAQ+ZWjPilE2qB/bB2vLWhBNuF+r35hWqkru1pEHEHY5667Xpf3nVhc5Qpe21lZjYs+ihn4zPJWod1hGqi4P93N4WKiWLQhZAZr/yo
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
