apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgAD9sNyJiaod/pigF+q53WwhBqG5r0ExbakdVn7gS83HvkeYPQ2a/Ewjyd0o0cx3H8JsLYVvQbLbZYnPXO1PcaQGeuAytPPoHRc0NevkragNWC6enu9HWOQQb/M8+o7diypwofzyl5sk8ba7tCQa6rp5Ij5VrGkqTuzGwYsbHrc53Uz3WJABbguHny55L6+6ULLAUOnZ2Os97ORhV6sotUqfEN8YBf4Yd3+pw1w9bNQ90AtFha5j2P/reCWwZHHwNI7mpN6y3usvHs7S3LVK5JUYYKLfUFffcdjxxHYUJnPjqQrE4WlCzvCssMc0iAR80PDOccMYShFSpOf2ATAd3vB0VLuc8dcDnIrDo+qz5W+5I6kz5MyQELBNT2auRbHIvBiR6gyYxVZFT0Zia4BtzRfci7pRKZwmg1ZoN6Uq4kP0tZj7Ij5wL23GOF+Z8GqWemxL/gmrOt3Veza8DAIpYaoApjz/qNutV0PAvMJNnuFDYXrwVwUMnpLqGoiTeAdLDBH4r717dR96rXEKE7Z5/4TZohFNoac3wTE2mgmjE/ztT9PHUm/MgeQvZTGd4CtPvSDEpy512pdxKr7idpHsucvpAUj3UrJ+h88lomF/gN8BdKEvyYBayXfauaBiuuQUsgOhHhTjyZL0BGzBTp6r4hymH5OiR4GhDBGPUd9N51GJKV0K2mTPwMZGUInV3wcgzcFKQl7g/vMBx4A4yoQmV2cnO9Vzi9OpEOlYY5Yr+I2vA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
