apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${BUILD_REPOSITORY_NAME}-app
  namespace: ${NAMESPACE}
  labels:
    service: app
spec:
  selector:
    matchLabels:
      service: app
  template:
    metadata:
      labels:
        service: app
    spec:
      containers:
        - image: ${IMAGE_TAG}
          name: app
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: ${NEXT_CPU_REQUESTS}
              memory: ${NEXT_MEMORY_REQUESTS}
          envFrom:
            - secretRef:
                name: ${BUILD_REPOSITORY_NAME}-general-secret
            - secretRef:
                name: city-gallery-strapi-revalidate-secret
            - configMapRef:
                name: ${BUILD_REPOSITORY_NAME}-env
          readinessProbe:
            httpGet:
              path: /
              port: ${INTERNAL_APP_PORT}
            timeoutSeconds: 5
            periodSeconds: 60
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      imagePullSecrets:
        - name: ${IMAGE_PULL_SECRET}
