apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MAILGUN_API_KEY: AgAuSBVIDq0oCvo4bOn7A/HxzNamVkeFu8ghjWQO8cGe/lhI68uqWmrK3dgrqJpD76Z1OVS21bbIj+nLhZ20kbwI0hGN8SBfW3eGHNSV4tccsgXbJce/+f1/76TZTV3x1mTiPu9TbT02pmR4LSEXWs9hBJfDk/U7no3KNOQZW3gCQtg+l0kK22WlM1GI6r6ver5wIiVu7W2h+gKVFMoZZTYWD+m0KcalmgsD1x6o+yVu5X4EVQgsWP4RXozUZmvLZVRqlbhszL3Ea4xrXxru3RxK5pN4etywDfgUl9av00XZSJgfj4sQf0zLSIBXcXmSGM6b1p3nSRFZqU7r6U1Y/HVhOxfm0TRrad2haqWqn8x9DNZdxL9ZFnfBtcmvzn+8LX7fnKMAkr7EJyPb+XmVEjOPaevUnELCPA3wk4+ePI4OO6k4/2nSXBPOTHTTVaoJOQDzlE6W7nieCPHoFIBMzdPPAMWiapEVjVSNK0LivjS9cRQKzc49nsUZvtnqNvEQphDo/FwM3B8TMHyevBLBZT98a6937nT/s16UWvwiSkmc6NPSHmPlgjh5lt8kZZNpLyM8MpOhZDPzlaYOULeyn4JB1poBc4ZVdq9zPGLxn3yiASY0Q2/LvQKLsk7UtxhOisUKMq9ZwMm0E0YI158WCwCHRSyn+adsF/k2l+hzHKIdcOo+46M7Wos5o9d5qYpEF/iqd+qsz+EuU9fXwYMTeFOvtheiruUs/E2sgeQ1jc4M941NGvQ/8Tre7EVyelcYN2yKvw==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-mailgun-secret
      namespace: ${NAMESPACE}
