apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: city-gallery-strapi-minio-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    MINIO_ACCESS_KEY: AgCixcSmiXYKmnPw9VcJdh6hz6qaMjqIlDOOtBG4ZjDUO/Z9tDlYzfXKpT8VrieygJJhF54/sAg9FIx0uHzWm83majV9Mx6RY0dU8dkLBsLVhtixEp2Jjslqf0tugMINxMsokCFv9s8H9VXpruZxApMxp4DmINBz3QM9KnGpVUx7nETH1zQo6mNuhje1ilBCCcvEKbKm1OfdsgQ0v+C8tGZlGnn/nhShlSVAibC/Hw27AF3URxI3Wxjkwx0QX5EevME2dqMdrSq9/qLq5M4YgPnqk2OyKR9Zq8FpB288iK0gso2F9/QQ6iB8itP7moJH6Y7873HYgyIRaHHTIVPW0lX+llaMIk/g/pcKu0qNpuWUAbWUhRaQbkRCfyUWJ3uU1aQgp7RQPv3VjDkbS9bJEO24l7ImfgR6+cmYn60cgEwL8BYSoA/1Lh6TRv8SUw6oTFF9HooTysdfq6W6280GBn7etzPstLK46Qjg5nDkfIAPu8QnQKKdzWLUG/rifDpW9Z2ByUc5BuwlKYwxrdTvFf7vRR2gEjT7j7JTY6xD9rAgcDfqmuJWyGxIympS/ZP+jUtI/BlaPEAahfNi7bhk0iFEg3ZtlNIvbRnnuWYzd2hZ3fwEonmp3z8EYjMXxEzFavKBllwFUY2L35T7z69/B6ojU4LHpISvrvMX9ok7O3dbA2z+YTG6QKdEbDFBoMI2SyCr70c=
    MINIO_SECRET_KEY: AgBSOh0DLRRR7JLCS7n4DHoVV6J+2R9TLALq7/h63Sph849ucGBRp6oD/iSDK8etUlIPujbmQAWsrYR2Vy2AmqWYzqdD8D0Bsh68Zvvaa1kz20YqoX3QIT9pjHyryttTU0NqE4a7fOK8K950170wmczBD25JbunewfqrNOrXMnLnLTCk/BJqomdIcpzanWoRGx4e+iwXoTwTwlJTOmfvkS5JpDvXsl/B5HdwpYAxmzb7vwy3uAeDHlpW1rMxBNnl7XCPN6Kdc/Xg/7CTHCShA3KFqZC2lfimUVnzEualidnIXh3cb+NIoZmrsTlezr6tWYQBdC5Rhuij5JHAxy2oHx6dVgcTTLTc5eJcbFxMCeUYALPzPqnB4jJQFO1MvqKuQTUFDNISDi5u4YioRAUqJlvBGY1KQEJgb+iyFfGfALhTaXn2effq23jT5SQDJ6iWhfgkwfu0DWOEgZqUbl/Ng6ClfM7QrNGZz0S+lixBB4eIZU3UyvH+Lpq7e7mpbRfznorgy2YkLGGNnsOTLLyQ2NYuhEYjOLepqB0wfMT19U/OpQFAeQ5xhLfGlJ3diME2Z57wPnN2EITysUYn9c6olwjLccJDeY+mdImLAqGrCWZcl+BHO5T0QESeS3ewQHzNVqUMXhjWO59E0Zj0NHMhr81FRFZhb+tMl8nSE8DwA6X/mxa45FOpNwG1Rw/6k5U3DfLnFREXpUpxoxwRsTNukAIY1jd08LnuicQXmu/LN/58UXD2orJ2QW2z8wSoKV5mEaYktpg/2cI2Sg==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: city-gallery-strapi-minio-secret
      namespace: ${NAMESPACE}
