apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgAqbOvQHCzoBh8Lpekegrz45TZ11rDobZ7vi1MO7ZraUhYoPSIwirB3pY55dy2GjD8LiqBjKxuyeHceoWji/a4OJy4zVXbdwL39pX3FaMN1QfWlRy4cI8MLWoZGbbHnq7ePmva2Xlh32Q0KfDDEz4nAfNLuY6Rlp4wSOKDZE/L/LAWIxKBTfdc3DVJ3AiSq5+9NWlnkvVswyeDh3rT+oJ2Yi40GZ/U9ElS6Bf4hVlOqR4c7Ej4HSbR6BXVr68DVpSfjbUIXiVic96LDNlymDbtgMNLKeMcG9Y2rwnqsx32dg1ZnmXV0dKIFrJI1hoLi4/9tTXEAqvtrLlZH7DMf8762r0XX6glkOgiXQd1lqPVV3boiVqnIODXI+3/ZEoIGtmCFB8TexxQJJNobEzytzaeRhJ3+bnb1+rjMzLig4kUscS0xJFHBAxTHeMcptpAxEsVH8uraPVGN9ATGBrxuJVLqeUsZdF1o/QwVbfYIzM6tSewTjcHrC4gku1T5isASiUJBx47vpzV84fOj0m6yNGy0cW++L8f70bknunF0CQs204pjfGc2QHbB8ktNFrBd9WaZqNWks4+G/nkgdbUzytz4UDLhAcdqU/hPGezpPga3/+qiWcd92QnD0n50Yo2ZbRzQPVR2KJfKdrOB5e1v4x0bRSDS5+lPambs1vuoZtwBMphnY0zhbfLeDbGS4ib1adK/GyD9askHluSqp45SW/I0o8V3ElPzgPgAuQD+VzL7
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
