apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: 'true'
  name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
  namespace: ${NAMESPACE}
  labels:
    app: ${BUILD_REPOSITORY_NAME}
    source: ${BUILD_REPOSITORY_NAME}
spec:
  encryptedData:
    REVALIDATE_SECRET_TOKEN: AgAmdP5r1TGNE9TFzNbjjtfRpPMy/nJNZHAMPxC8izrGoHJ11vsMHbAWV2Dcp4bhqTyiDO0TyRnj5TrySQY3GIU5LbketFp7hyS2I5BZUGkIfCl6I5Z6kmkWX2AZkWslpEcCSR1Sb3G1pa2VqE6aNm4t/IeYTTcfpD90gO1HN2qCI9Z/ZylnRqR38140VgpZLxyjkUJXdt/QjgDTtr46oRJH8gXNiOhSjKEUE+VfYe8HbLlf9JWqPydS1x0hgaocNQkWdvzXvokq/DxISEm4/RiLg3UDYQQAuykfwR+WsQYmQtVpeS+EsXxH5DN+XW3QfPoUapNC4tiuIoZ+vLEgA8uqKaSPEAFFcqR894gI4EC03P5DstBKciC5ykcLxPQ2K+p+kbOKc3DW5EmQbJG3IkwgihTvYmgUy2yRI0Fjof4y4JT0Y8W1JrMJCaJUt1neD2BeWWrpPdaO/hoAZaelEeFkC3LWBDwCI7crzg8AK/ieEfKJZNO8xwUYM58IgUuuYIpDPu9vnh384P4ktsYPwRkzyilSnmGBaHzohRE5KIauN46YYYYeKhO0YSNjsT9ytgdNLs/yCHcSecn2TFyT0bGXOS24Lr2eGsGtVjhBHt5pj8fFeBENQ4Inuqlbcf+dkozC3+gvOkaGbsus9UbTiXjzfkvhxuWSnpCBbUtz9HqYgvfSK+4v+mMqsLzJ2NzZJYRZS4QtgqcwuvLOwzHrv1aM9M+uyanKGDpdeL0L+LiEjA==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: 'true'
      labels:
        app: ${BUILD_REPOSITORY_NAME}
        source: ${BUILD_REPOSITORY_NAME}
      name: ${BUILD_REPOSITORY_NAME}-revalidate-secret
      namespace: ${NAMESPACE}
