query General($locale: I18NLocaleCode!) {
  general(locale: $locale) {
    data {
      ...GeneralEntity
    }
  }
}

query Places($locale: I18NLocaleCode!) {
  places(locale: $locale) {
    data {
      attributes {
        title
        slug
        address
      }
    }
  }
}

query TagsByCategorySlug($locale: I18NLocaleCode!, $tag: String!) {
  tagCategoryBySlug(locale: $locale, slug: $tag) {
    data {
      attributes {
        tags(sort: "id:asc", pagination: { limit: 100 }) {
          data {
            ...TagEntity
          }
        }
      }
    }
  }
}

query News($locale: I18NLocaleCode!, $tag: String!, $limit: Int = 5, $sort: [String] = ["publishedAt:desc"]) {
  news: contentPages(
    locale: $locale
    sort: $sort
    pagination: { limit: $limit }
    filters: { tags: { slug: { eq: $tag } } }
  ) {
    data {
      ...NewsItemEntity
    }
  }
}

query PreviewsByTags(
  $locale: I18NLocaleCode!
  $limit: Int
  $offset: Int
  $tagSlugs: [String]
  $placesSlugs: [String]
  $dateForFilteringPastEvents: Date
  $dateForFilteringFutureEvents: Date
  $sort: [String] = ["dateFrom:desc", "publishedAt:desc"] # keeping this default sorting as it was before
) {
  contentPages(
    locale: $locale
    pagination: { start: $offset, limit: $limit }
    filters: { tags: { slug: { in: $tagSlugs } }, place: { slug: { in: $placesSlugs } }, dateTo: { lt: $dateForFilteringPastEvents, gt: $dateForFilteringFutureEvents } }
    sort: $sort
  ) {
    data {
      ...SectionItemEntity
    }
  }
}

query PreviewContentPageBySlug($slug: String!) {
  contentPageBySlug(slug: $slug, locale: "all") {
    data {
      attributes {
        slug
        locale
      }
    }
  }
}

query ContentPageBySlug($locale: I18NLocaleCode!, $slug: String!, $isPublished: Boolean!) {
  contentPageBySlug(slug: $slug, locale: $locale, isPublished: $isPublished) {
    data {
      ...ContentPageEntity
    }
  }
}

query AllContentPageSlugs($locale: I18NLocaleCode!) {
  contentPages(locale: $locale) {
    data {
      attributes {
        slug
        locale
      }
    }
  }
}

query ExhibitionsByPlace(
  $locale: I18NLocaleCode!
  $slug: String!
  $today: Date!
  $tagExhibitions: String!
  $tagPermanentExhibitions: String!
  $place: String!
) {
  currentEvents: contentPages(
    locale: $locale
    filters: {
      or: [
        { tags: { slug: { eq: $tagPermanentExhibitions } } }
        {
          tags: { slug: { eq: $tagExhibitions } }
          or: [{ dateFrom: { lte: $today }, dateTo: { gte: $today } }, { dateFrom: { eq: $today } }]
        }
      ]
      place: { slug: { eq: $place } }
      slug: { ne: $slug }
    }
  ) {
    data {
      ...SectionItemEntity
    }
  }
}

query AboutUsPage($locale: I18NLocaleCode!) {
  aboutUsPage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlight
        }
        sections {
          ...Sections
        }
        seo {
          ...Seo
        }
      }
    }
  }
}

query HomePage($locale: I18NLocaleCode!) {
  homePage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlight
        }
        sections {
          ...Sections
        }
        partners {
          partner {
            data {
              ...PartnerEntity
            }
          }
        }
        seo {
          ...Seo
        }
      }
    }
  }
}

query CollectionPage($locale: I18NLocaleCode!) {
  collectionsPage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlight
        }
        sections {
          ...Sections
        }
        seo {
          ...Seo
        }
      }
    }
  }
}

query GetInvolvedPage($locale: I18NLocaleCode!) {
  getInvolvedPage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlight
        }
        sections {
          ...Sections
        }
        seo {
          ...Seo
        }
      }
    }
  }
}

query VisitUsPage($locale: I18NLocaleCode!) {
  visitUsPage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlight
        }
        sections {
          ...Sections
        }
        seo {
          ...Seo
        }
      }
    }
  }
  tickets(locale: $locale) {
    data {
      ...TicketEntity
    }
  }
}

query ExplorePage($locale: I18NLocaleCode!) {
  explorePage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlight
        }
        seo {
          ...Seo
        }
      }
    }
  }
}

query ExhibitionsPage(
  $locale: I18NLocaleCode!
  $today: Date!
  $tagExhibitions: String!
  $tagPermanentExhibitions: String!
  $tagsAdditionalProgram: [String]!
) {
  exhibitionsPage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlight
        }
        archiveSection {
          ...ArchiveSection
        }
        seo {
          ...Seo
        }
      }
    }
  }
  exhibitions: contentPages(
    locale: $locale
    filters: { tags: { slug: { eq: $tagExhibitions } }, dateTo: { gte: $today } }
  ) {
    data {
      ...SectionItemEntity
    }
  }
  permanentExhibitions: contentPages(
    locale: $locale
    filters: { tags: { slug: { eq: $tagPermanentExhibitions } }, dateFrom: { lte: $today } }
  ) {
    data {
      ...SectionItemEntity
    }
  }
  additionalProgram: contentPages(
    locale: $locale
    filters: { tags: { slug: { in: $tagsAdditionalProgram } }, dateTo: { gte: $today } }
    sort: ["dateFrom:asc"]
  ) {
    data {
      ...SectionItemEntity
    }
  }
}

query ArchivePage($locale: I18NLocaleCode!) {
  archivePage: exhibitionsPage(locale: $locale) {
    data {
      attributes {
        __typename
        archiveSeo {
          ...Seo
        }
      }
    }
  }
}

query DisclosureOfInformationPage($locale: I18NLocaleCode!) {
  general(locale: $locale) {
    data {
      attributes {
        disclosureMoreFiles {
          title
          submenuTitle
          files {
            ...DownloadItem
          }
        }
      }
    }
  }
}

