query Places($locale: I18NLocaleCode!) {
  places(locale: $locale) {
    data {
      attributes {
        title
        slug
      }
    }
  }
}

query TagsByCategorySlug($locale: I18NLocaleCode!, $tag: String!) {
  tagCategoryBySlug(locale: $locale, slug: $tag) {
    data {
      attributes {
        tags {
          data {
            attributes {
              title
              slug
            }
          }
        }
      }
    }
  }
}

query News(
  $locale: I18NLocaleCode!
  $tag: String!
  $limit: Int = 5
  $sort: [String] = ["created_at:desc"]
) {
  news: contentPages(
    locale: $locale
    sort: $sort
    pagination: { limit: $limit }
    filters: { tags: { slug: { eq: $tag } } }
  ) {
    data {
      attributes {
        ...NewsItem
      }
    }
  }
}

query PreviewsByTags(
  $locale: I18NLocaleCode!
  $limit: Int
  $offset: Int
  $tagSlugs: [String]!
  $placesSlugs: [String]!
) {
  contentPages(
    locale: $locale
    pagination: { start: $offset, limit: $limit }
    filters: {
      tags: { slug: { in: $tagSlugs } }
      place: { slug: { in: $placesSlugs } }
    }
  ) {
    data {
      attributes {
        ...SectionItem
      }
    }
  }
}

query ContentPageBySlug($locale: I18NLocaleCode!, $slug: String!) {
  contentPageBySlug(slug: $slug, locale: $locale) {
    data {
      attributes {
        ...ContentPage
      }
    }
  }
  contact(locale: $locale) {
    data {
      attributes {
        ...ContactAndFooter
      }
    }
  }
}

query TicketPageBySlug($locale: I18NLocaleCode!, $slug: String!) {
  contentPageBySlug(slug: $slug, locale: $locale) {
    data {
      attributes {
        ...ContentPage
      }
    }
  }
  contact(locale: $locale) {
    data {
      attributes {
        ...ContactAndFooter
      }
    }
  }
}

query AboutUsPage($locale: I18NLocaleCode!) {
  aboutUsPage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlights
        }
        sections {
          ...Sections
        }
        seo {
          ...Seo
        }
      }
    }
  }
  contact(locale: $locale) {
    data {
      attributes {
        ...ContactAndFooter
      }
    }
  }
}

query HomePage($locale: I18NLocaleCode!) {
  homePage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlights
        }
        sections {
          ...Sections
        }
        # partnersSection {
        #   partners {
        #     ...Partner
        #   }
        # }
        seo {
          ...Seo
        }
      }
    }
  }
  contact(locale: $locale) {
    data {
      attributes {
        ...ContactAndFooter
      }
    }
  }
}

query CollectionPage($locale: I18NLocaleCode!) {
  collectionsPage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlights
        }
        sections {
          ...Sections
        }
        seo {
          ...Seo
        }
      }
    }
  }
  contact(locale: $locale) {
    data {
      attributes {
        ...ContactAndFooter
      }
    }
  }
}

query GetInvolvedPage($locale: I18NLocaleCode!) {
  getInvolvedPage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlights
        }
        sections {
          ...Sections
        }
        seo {
          ...Seo
        }
      }
    }
  }
  contact(locale: $locale) {
    data {
      attributes {
        ...ContactAndFooter
      }
    }
  }
}

query VisitUsPage($locale: I18NLocaleCode!) {
  visitUsPage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlights
        }
        sections {
          ...Sections
        }
        seo {
          ...Seo
        }
      }
    }
  }
  tickets {
    data {
      attributes {
        ...Ticket
      }
    }
  }
  contact(locale: $locale) {
    data {
      attributes {
        ...ContactAndFooter
      }
    }
  }
}

query ExplorePage($locale: I18NLocaleCode!) {
  explorePage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlights
        }
        seo {
          ...Seo
        }
      }
    }
  }
  contact(locale: $locale) {
    data {
      attributes {
        ...ContactAndFooter
      }
    }
  }
}

query ExhibitionsPage(
  $locale: I18NLocaleCode!
  $today: Date!
  $tagExhibitions: String!
  $tagExpositions: String!
) {
  exhibitionsPage(locale: $locale) {
    data {
      attributes {
        __typename
        highlights {
          ...Highlights
        }
        seo {
          ...Seo
        }
      }
    }
  }
  exhibitions: contentPages(
    locale: $locale
    filters: {
      tags: { slug: { eq: $tagExhibitions } }
      or: [{ dateFrom: { gte: $today } }, { dateTo: { gte: $today } }]
    }
  ) {
    data {
      attributes {
        ...SectionItem
      }
    }
  }
  expositions: contentPages(
    locale: $locale
    filters: {
      tags: { slug: { eq: $tagExpositions } }
      or: [{ dateFrom: { gte: $today } }, { dateTo: { gte: $today } }]
    }
  ) {
    data {
      attributes {
        ...SectionItem
      }
    }
  }
  additionalProgram: contentPages(
    locale: $locale
    filters: {
      tags: { slug: { notIn: [$tagExhibitions, $tagExpositions] } }
      or: [{ dateFrom: { gte: $today } }, { dateTo: { gte: $today } }]
    }
  ) {
    data {
      attributes {
        ...SectionItem
      }
    }
  }
  contact(locale: $locale) {
    data {
      attributes {
        ...ContactAndFooter
      }
    }
  }
}

query ErrorPage($locale: I18NLocaleCode!) {
  contact(locale: $locale) {
    data {
      attributes {
        ...ContactAndFooter
      }
    }
  }
}

fragment Image on UploadFile {
  url
  alternativeText
  width
  height
}

fragment Ticket on Ticket {
  title
  price
  link
  description
}

fragment Partner on Partner {
  title
  logo {
    data {
      attributes {
        ...Image
      }
    }
  }
  link
}

fragment Tag on Tag {
  title
  slug
}

fragment Place on Place {
  title
  slug
}

fragment Position on ComponentBlocksPositionItem {
  title
  names
}

fragment Datetime on ContentPage {
  dateFrom
  dateTo
  timeFrom
  timeTo
  showRemainingTime
}

fragment ContentPagePlace on ContentPage {
  place {
    data {
      attributes {
        ...Place
      }
    }
  }
  placeTitle
  placeAddress
}

fragment Positions on ContentPage {
  positions {
    ...Position
  }
}

fragment Partners on ContentPage {
  partners {
    data {
      attributes {
        ...Partner
      }
    }
  }
}

fragment SliderMedia on UploadFile {
  alternativeText
  url
}

fragment SliderSection on ComponentSectionsSliderSection {
  id
  submenuTitle
  medias {
    data {
      attributes {
        ...SliderMedia
      }
    }
  }
}

fragment Seo on ComponentBlocksSeo {
  metaTitle
  metaDescription
  keywords
  metaRobots
  metaViewport
  canonicalUrl
}

fragment ContentPage on ContentPage {
  title
  subtitle
  slug
  coverMedia {
    data {
      attributes {
        url
        alternativeText
      }
    }
  }
  perex
  color
  inheritColorFromParent
  ...Datetime
  ...ContentPagePlace
  ...Positions
  ...Partners
  purchaseId
  mainContent {
    ...MainContent
  }
  slider {
    ...SliderSection
  }
  relatedContentTitle
  relatedContentSubmenuTitle
  downloadSection {
    ...DownloadSection
  }
  parentPage {
    data {
      attributes {
        color
      }
    }
  }
  childPages {
    data {
      attributes {
        ...SectionItem
      }
    }
  }
  tags {
    data {
      attributes {
        ...Tag
      }
    }
  }
  seo {
    ...Seo
  }
  localizations {
    data {
      attributes {
        slug
        locale
      }
    }
  }
}

fragment NewsItem on ContentPage {
  title
  subtitle
  slug
  color
  inheritColorFromParent
  parentPage {
    data {
      attributes {
        color
      }
    }
  }
}

fragment SectionItem on ContentPage {
  ...NewsItem
  perex
  coverMedia {
    data {
      attributes {
        alternativeText
        url
      }
    }
  }
  dateFrom
  dateTo
  tags {
    data {
      attributes {
        ...Tag
      }
    }
  }
}

fragment DownloadItem on ComponentBlocksFileItem {
  id
  title
  file {
    data {
      attributes {
        name
        caption
        alternativeText
        ext
        size
        url
      }
    }
  }
}

fragment HighlightsItem on ContentPage {
  ...SectionItem
  ...Datetime
  ...ContentPagePlace
  ...Positions
  purchaseId
  override {
    highlightContent
  }
}

fragment Highlights on ComponentSectionsHighlightsSection {
  contentPages {
    data {
      attributes {
        ...HighlightsItem
      }
    }
  }
}

fragment PalaceDetails on ComponentBlocksPalace {
  title
  address
  zip
  city
  phone
}

fragment ContactAndFooter on Contact {
  name
  email
  openingHours
  mirbach {
    ...PalaceDetails
  }
  palffy {
    ...PalaceDetails
  }
  quickLinks {
    title
    url
  }
}

fragment ContactSection on ComponentSectionsContactSection {
  id
  submenuTitle
}

fragment PageSection on ComponentSectionsPageSection {
  id
  title
  submenuTitle
  layout
  contentPages {
    data {
      attributes {
        ...SectionItem
      }
    }
  }
}

fragment NewsSection on ComponentSectionsNewsSection {
  id
  title
  submenuTitle
}

fragment NewsletterSection on ComponentSectionsNewsletterSection {
  id
  submenuTitle
}

fragment RichtextSection on ComponentSectionsRichtextSection {
  id
  submenuTitle
  content
}

fragment VideoSection on ComponentSectionsVideoSection {
  id
  title
  submenuTitle
  url
}

fragment TicketsSection on ComponentSectionsTicketsSection {
  id
  title
  submenuTitle
  text
}

fragment MapSection on ComponentSectionsMapSection {
  id
  title
  submenuTitle
}

fragment DownloadSection on ComponentSectionsDownloadSection {
  id
  title
  submenuTitle
  files {
    ...DownloadItem
  }
}

fragment Sections on VisitUsPageSectionsDynamicZone {
  ... on ComponentSectionsPageSection {
    __typename
    ...PageSection
  }
  ... on ComponentSectionsNewsSection {
    __typename
    ...NewsSection
  }
  ... on ComponentSectionsContactSection {
    __typename
    ...ContactSection
  }
  ... on ComponentSectionsNewsletterSection {
    __typename
    ...NewsletterSection
  }
  ... on ComponentSectionsTicketsSection {
    __typename
    ...TicketsSection
  }
  ... on ComponentSectionsMapSection {
    __typename
    ...MapSection
  }
  ... on ComponentSectionsRichtextSection {
    __typename
    ...RichtextSection
  }
}

fragment MainContent on ContentPageMainContentDynamicZone {
  ... on ComponentSectionsRichtextSection {
    __typename
    ...RichtextSection
  }
  ... on ComponentSectionsVideoSection {
    __typename
    ...VideoSection
  }
}
